## By default the alu demo YAML, more features to be added...
##    - overhauling the YAML is a big Ver 2.0 target

DUT:
    Module: alu
    Dependencies:
        Packages: 
            alu_pkg.svh: alu_pkg
        Includes:
    Parameters: 
        DATA_W: 16
    Ports:
        Clock: clk
        Active_Low_Reset: n_rst
        In: 
            opcode: '[1:0]'
            a: '[(DATA_W-1):0]'
            b: '[(DATA_W-1):0]'
        Out: 
            out: '[(DATA_W-1):0]'
            negative: ''
            overflow: ''
            zero: ''

Testbench:
    Modport:

Output_Path: alu/MyUVMF/